---
title: "synthesis exercise"
author: "Marta Españó López"
date: "6/6/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Marta Espano Lopez
104532


Link to my github repository:
https://github.com/Martaesplo/omics_techniques.git



```{r packages, echo=FALSE}
installifnot <- function (pkg){
  if (!require(pkg, character.only=T)){
  source("http://bioconductor.org/install")
  biocLite(pkg)
}else{
  require(pkg, character.only=T)
  }
}

installifnot("pd.mogene.1.0.st.v1")
BiocManager::install("mogene10sttranscriptcluster.db")
installifnot("oligo")
installifnot("limma")
installifnot("Biobase")
# installifnot("arrayQualityMetrics")
BiocManager::install("genefilter")
BiocManager::install("multtest")
BiocManager::install("annotate")
install("gplots")
installifnot("scatterplot3d")
```

```{r libraries, echo=FALSE}
library(methods)
library(Biobase)
library(BiocManager)
library(BiocVersion)
library(GEOquery)
library(limma)
library(pd.mogene.1.0.st.v1)
library(mogene10sttranscriptcluster.db)
library(oligo)
library(limma)
library(genefilter)
library(multtest)
library(annotate)
library(gplots)
library(scatterplot3d)
```



```{r targets}
workingDir <-getwd() # Remember to first do Session/Set working directory
dataDir <- file.path(workingDir, "/dataset")
resultsDir <- file.path(workingDir, "/results")
setwd(workingDir)
workingDir
```

```{r echo=FALSE}
gse <- getGEO("GSE52553")
eset<-gse[[1]]
rdeset<-(eset[1:11,c(1,2,3,4,43,44,65,66,69,70,29,30)])
dim(exprs(rdeset))
dim(exprs(eset))

head(rdeset)
head(exprs(rdeset))
targets<-pData(rdeset)
exprs(rdeset)
length(exprs(eset[1,1]))

rdset



```

```{r}

pcs<-prcomp(exprs(rdeset))
pcs
barplot(pcs$sdev)
plot(pcs$rotation[,1], pcs$rotation[,2], main="Representation of first two principal components")
?rpois
#################


```




```{r geod2}
gse2<- getGEO('GSE69078')
eset2<-gse2[[1]]
eset2
dim(exprs(eset2))
```

```{r targets}
```

```{r targets}
```








